from re import I
from typing import Dict

import pytest


@pytest.fixture
def basic_album_qobuz_response() -> Dict[str, object]:
    return dict(
        id="foo",
        title="bar",
        tracks_count=1,
        genres_list=["Rock", "Pop"],
        release_date_original="2022-01-01",
        copyright="(C) abc 123, llc",
        artists=[dict(id=1, name="Johnny Appleseed", roles=["main-artist"])],
        composer=dict(
            id=1,
            name="Hans Zimmer",
            slug="hans-zimmer",
            albums_count=1,
            picture=None,
            image=None,
        ),
        label=dict(
            name="abc 123, llc", id=1, albums_count=1, supplier_id=1, slug="abc-123-llc"
        ),
        description="Not a real album",
        tracks=dict(
            offset=0,
            limit=100,
            total=1,
            items=[
                dict(
                    maximum_bit_depth=16,
                    copyright="(C) 2022 abc 123, llc",
                    performers="Johnny Appleseed",
                    audio_info=dict(
                        replaygain_track_peak=0.123, replaygain_track_gain=0.456
                    ),
                    performer=dict(name="Johnny Appleseed", id=1),
                    work=None,
                    composer=dict(name="Hans Zimmer", id=1),
                    isrc="USA123456",
                    title="Hello World",
                    version=None,
                    duration=10,
                    parental_warning=False,
                    track_number=1,
                    maximum_channel_count=2,
                    id=1234,
                    media_number=1,
                    maximum_sampling_rate=44.1,
                    relase_date_original=None,
                    release_date_download=None,
                    release_date_stream=None,
                    purchasable=True,
                    streamable=True,
                    previewable=True,
                    sampleable=True,
                    downloadable=True,
                    displayable=True,
                    purchasable_at=1647932400,
                    streamable_at=1647932400,
                    hires=False,
                    hires_streamable=False,
                )
            ],
        ),
        parental_warning=False,
        image=dict(
            small="https://foo.com/small.jpg",
            thumbnail="https://foo.com/thumb.jpg",
            large="https://foo.com/large.jpg",
            back=None,
        ),
        streamable=True,
        maximum_bit_depth=16,
        maximum_sampling_rate=44.1,
        goodies=[],
    )


@pytest.fixture
def monty_python_holy_grail_album_resp() -> Dict[str, object]:
    return dict(
        id="lj1s9oz62wsqb",
        title="The Album Of The Soundtrack Of The Trailer Of The Film Of Monty Python And The Holy Grail",
        tracks_count=27,
        genres_list=["Film", "Film→Bandes originales de films"],
        release_date_original="1975-07-18",
        copyright="(P) 2006 Arista Records, LLC",
        artists=[{"id": 44279, "name": "Monty Python", "roles": ["main-artist"]}],
        composer=dict(
            id=573076,
            name="Various Composers",
            slug="various-composers",
            albums_count=583621,
            picture=None,
            image=None,
        ),
        label=dict(
            name="Arista - Legacy",
            id=4625,
            albums_count=465,
            supplier_id=23,
            slug="arista-legacy",
        ),
        description='The actual title of this release is "The Album of the Soundtrack of the Trailer of the Film of Monty Python and the Holy Grail (1975)." As such, a majority of the disc consists of extracts from the motion picture\'s dialogue. This is a different approach from what writer/actors Michael Palin, Graham Chapman, John Cleese, Eric Idle, Terry Jones, and Terry Gilliam (also visual designer) had taken with their previous studio outings, which were in essence re-recordings of classic sketches from the Monty Python\'s Flying Circus television program. For the sake of continuity, several new bits have been added; chief among these are Chapman\'s assorted "Executive Edition" announcements, concluding with the "verrrry nice" "Executive Edition Addendum." For the "Tour of the Classic Silbury Hill Theatre" and "Live Broadcast from London: Premiere of the Film," Palin and Cleese provide setting and exposition for both the album and the film. At times they mock the visual aspects and the very nature of the cinematic experience as it translates (or fails to translate) onto vinyl. Much of what is included here has become legendary among the faithful, as well as definitive within the Python repertoire, most notably "Bring Out Your Dead," "A Witch," "The Knights Who Say \'Ni!\'," and "Camelot," the Hollywood-style production number written by former Bonzo Dog Doo Dah Band member Neil Innes, who also provided all the songs for the flick.\n<br />&copy  Lindsay Planer /TiVo',
        tracks=dict(
            offset=0,
            limit=500,
            total=27,
            items=[
                {
                    "maximum_bit_depth": 16,
                    "copyright": "(P) 1975, 1997 Arista Records, LLC",
                    "performers": "Not Documented, Producer - Eric Idle, Composer, Lyricist - Terry Jones, Composer, Lyricist - John Cleese, Composer, Lyricist - Graham Chapman, Composer, Lyricist - Terry Gilliam, Composer, Lyricist - Monty Python, MainArtist, AssociatedPerformer - Michael Palin, Composer, Lyricist",
                    "audio_info": {
                        "replaygain_track_peak": 0.884918,
                        "replaygain_track_gain": 0.06,
                    },
                    "performer": {"name": "Monty Python", "id": 44279},
                    "work": None,
                    "composer": {"name": "Graham Chapman", "id": 675365},
                    "isrc": "USAR10700137",
                    "title": "Introduction",
                    "version": None,
                    "duration": 67,
                    "parental_warning": False,
                    "track_number": 1,
                    "maximum_channel_count": 2,
                    "id": 47062480,
                    "media_number": 1,
                    "maximum_sampling_rate": 44.1,
                    "release_date_original": None,
                    "release_date_download": None,
                    "release_date_stream": None,
                    "purchasable": True,
                    "streamable": True,
                    "previewable": True,
                    "sampleable": True,
                    "downloadable": True,
                    "displayable": True,
                    "purchasable_at": 1647932400,
                    "streamable_at": 1647932400,
                    "hires": False,
                    "hires_streamable": False,
                },
                {
                    "maximum_bit_depth": 16,
                    "copyright": "(P) 1975, 1997 Arista Records, LLC",
                    "performers": "Not Documented, Producer - Eric Idle, Composer, Lyricist - Terry Jones, Composer, Lyricist - John Cleese, Composer, Lyricist - Graham Chapman, Composer, Lyricist - Terry Gilliam, Composer, Lyricist - Monty Python, MainArtist, AssociatedPerformer - Michael Palin, Composer, Lyricist",
                    "audio_info": {
                        "replaygain_track_peak": 0.991821,
                        "replaygain_track_gain": -2.3,
                    },
                    "performer": {"name": "Monty Python", "id": 44279},
                    "work": None,
                    "composer": {"name": "Graham Chapman", "id": 675365},
                    "isrc": "USAR10700138",
                    "title": "Introduction (Part 2)",
                    "version": None,
                    "duration": 242,
                    "parental_warning": False,
                    "track_number": 2,
                    "maximum_channel_count": 2,
                    "id": 47062481,
                    "media_number": 1,
                    "maximum_sampling_rate": 44.1,
                    "release_date_original": None,
                    "release_date_download": None,
                    "release_date_stream": None,
                    "purchasable": True,
                    "streamable": True,
                    "previewable": True,
                    "sampleable": True,
                    "downloadable": True,
                    "displayable": True,
                    "purchasable_at": 1647932400,
                    "streamable_at": 1647932400,
                    "hires": False,
                    "hires_streamable": False,
                },
                {
                    "maximum_bit_depth": 16,
                    "copyright": "(P) 1975, 1997 Arista Records, LLC",
                    "performers": "Not Documented, Producer - Eric Idle, Composer, Lyricist - Terry Jones, Composer, Lyricist - John Cleese, Composer, Lyricist - Graham Chapman, Composer, Lyricist - Terry Gilliam, Composer, Lyricist - Monty Python, MainArtist, AssociatedPerformer - Michael Palin, Composer, Lyricist",
                    "audio_info": {
                        "replaygain_track_peak": 0.99115,
                        "replaygain_track_gain": -1.81,
                    },
                    "performer": {"name": "Monty Python", "id": 44279},
                    "work": None,
                    "composer": {"name": "Graham Chapman", "id": 675365},
                    "isrc": "USAR10700139",
                    "title": "Arrival At Castle",
                    "version": None,
                    "duration": 162,
                    "parental_warning": False,
                    "track_number": 3,
                    "maximum_channel_count": 2,
                    "id": 47062482,
                    "media_number": 1,
                    "maximum_sampling_rate": 44.1,
                    "release_date_original": None,
                    "release_date_download": None,
                    "release_date_stream": None,
                    "purchasable": True,
                    "streamable": True,
                    "previewable": True,
                    "sampleable": True,
                    "downloadable": True,
                    "displayable": True,
                    "purchasable_at": 1647932400,
                    "streamable_at": 1647932400,
                    "hires": False,
                    "hires_streamable": False,
                },
                {
                    "maximum_bit_depth": 16,
                    "copyright": "(P) 1975, 1997 Arista Records, LLC",
                    "performers": "Not Documented, Producer - Monty Python, MainArtist, AssociatedPerformer - Fred Trombey, Composer, Lyricist",
                    "audio_info": {
                        "replaygain_track_peak": 0.70578,
                        "replaygain_track_gain": -0.65,
                    },
                    "performer": {"name": "Monty Python", "id": 44279},
                    "work": None,
                    "composer": {"name": "Fred Trombey", "id": 702354},
                    "isrc": "USAR10700140",
                    "title": "Constitutional Peasants",
                    "version": None,
                    "duration": 177,
                    "parental_warning": False,
                    "track_number": 4,
                    "maximum_channel_count": 2,
                    "id": 47062483,
                    "media_number": 1,
                    "maximum_sampling_rate": 44.1,
                    "release_date_original": None,
                    "release_date_download": None,
                    "release_date_stream": None,
                    "purchasable": True,
                    "streamable": True,
                    "previewable": True,
                    "sampleable": True,
                    "downloadable": True,
                    "displayable": True,
                    "purchasable_at": 1647932400,
                    "streamable_at": 1647932400,
                    "hires": False,
                    "hires_streamable": False,
                },
                {
                    "maximum_bit_depth": 16,
                    "copyright": "(P) 1975, 1997 Arista Records, LLC",
                    "performers": "Not Documented, Producer - Eric Idle, Composer, Lyricist - Terry Jones, Composer, Lyricist - John Cleese, Composer, Lyricist - Graham Chapman, Composer, Lyricist - Terry Gilliam, Composer, Lyricist - Monty Python, MainArtist, AssociatedPerformer - Michael Palin, Composer, Lyricist",
                    "audio_info": {
                        "replaygain_track_peak": 0.572754,
                        "replaygain_track_gain": -0.1,
                    },
                    "performer": {"name": "Monty Python", "id": 44279},
                    "work": None,
                    "composer": {"name": "Graham Chapman", "id": 675365},
                    "isrc": "USAR10700141",
                    "title": "Witch Burning",
                    "version": None,
                    "duration": 167,
                    "parental_warning": False,
                    "track_number": 5,
                    "maximum_channel_count": 2,
                    "id": 47062484,
                    "media_number": 1,
                    "maximum_sampling_rate": 44.1,
                    "release_date_original": None,
                    "release_date_download": None,
                    "release_date_stream": None,
                    "purchasable": True,
                    "streamable": True,
                    "previewable": True,
                    "sampleable": True,
                    "downloadable": True,
                    "displayable": True,
                    "purchasable_at": 1647932400,
                    "streamable_at": 1647932400,
                    "hires": False,
                    "hires_streamable": False,
                },
                {
                    "maximum_bit_depth": 16,
                    "copyright": "(P) 1975, 1997 Arista Records, LLC",
                    "performers": "Not Documented, Producer - Eric Idle, Composer, Lyricist - Terry Jones, Composer, Lyricist - John Cleese, Composer, Lyricist - Graham Chapman, Composer, Lyricist - Terry Gilliam, Composer, Lyricist - Monty Python, MainArtist, AssociatedPerformer - Michael Palin, Composer, Lyricist",
                    "audio_info": {
                        "replaygain_track_peak": 0.768219,
                        "replaygain_track_gain": -0.3,
                    },
                    "performer": {"name": "Monty Python", "id": 44279},
                    "work": None,
                    "composer": {"name": "Graham Chapman", "id": 675365},
                    "isrc": "USAR10700142",
                    "title": "Logician",
                    "version": None,
                    "duration": 173,
                    "parental_warning": False,
                    "track_number": 6,
                    "maximum_channel_count": 2,
                    "id": 47062485,
                    "media_number": 1,
                    "maximum_sampling_rate": 44.1,
                    "release_date_original": None,
                    "release_date_download": None,
                    "release_date_stream": None,
                    "purchasable": True,
                    "streamable": True,
                    "previewable": True,
                    "sampleable": True,
                    "downloadable": True,
                    "displayable": True,
                    "purchasable_at": 1647932400,
                    "streamable_at": 1647932400,
                    "hires": False,
                    "hires_streamable": False,
                },
                {
                    "maximum_bit_depth": 16,
                    "copyright": "(P) 1975, 1997 Arista Records, LLC",
                    "performers": "Not Documented, Producer - Eric Idle, Composer, Lyricist - Terry Jones, Composer, Lyricist - John Cleese, Composer, Lyricist - Graham Chapman, Composer, Lyricist - Terry Gilliam, Composer, Lyricist - Monty Python, MainArtist, AssociatedPerformer - Michael Palin, Composer, Lyricist",
                    "audio_info": {
                        "replaygain_track_peak": 0.584503,
                        "replaygain_track_gain": 0.2,
                    },
                    "performer": {"name": "Monty Python", "id": 44279},
                    "work": None,
                    "composer": {"name": "Graham Chapman", "id": 675365},
                    "isrc": "USAR10700143",
                    "title": "Camelot",
                    "version": None,
                    "duration": 27,
                    "parental_warning": False,
                    "track_number": 7,
                    "maximum_channel_count": 2,
                    "id": 47062486,
                    "media_number": 1,
                    "maximum_sampling_rate": 44.1,
                    "release_date_original": None,
                    "release_date_download": None,
                    "release_date_stream": None,
                    "purchasable": True,
                    "streamable": True,
                    "previewable": True,
                    "sampleable": True,
                    "downloadable": True,
                    "displayable": True,
                    "purchasable_at": 1647932400,
                    "streamable_at": 1647932400,
                    "hires": False,
                    "hires_streamable": False,
                },
                {
                    "maximum_bit_depth": 16,
                    "copyright": "(P) 1975, 1997 Arista Records, LLC",
                    "performers": "Not Documented, Producer - Neil Innes, Composer, Lyricist - John Cleese, Composer, Lyricist - Graham Chapman, Composer, Lyricist - Monty Python, MainArtist, AssociatedPerformer",
                    "audio_info": {
                        "replaygain_track_peak": 0.823853,
                        "replaygain_track_gain": -2.98,
                    },
                    "performer": {"name": "Monty Python", "id": 44279},
                    "work": None,
                    "composer": {"name": "Graham Chapman", "id": 675365},
                    "isrc": "USAR10700144",
                    "title": "Camelot Song",
                    "version": None,
                    "duration": 67,
                    "parental_warning": False,
                    "track_number": 8,
                    "maximum_channel_count": 2,
                    "id": 47062487,
                    "media_number": 1,
                    "maximum_sampling_rate": 44.1,
                    "release_date_original": None,
                    "release_date_download": None,
                    "release_date_stream": None,
                    "purchasable": True,
                    "streamable": True,
                    "previewable": True,
                    "sampleable": True,
                    "downloadable": True,
                    "displayable": True,
                    "purchasable_at": 1647932400,
                    "streamable_at": 1647932400,
                    "hires": False,
                    "hires_streamable": False,
                },
                {
                    "maximum_bit_depth": 16,
                    "copyright": "(P) 1975, 1997 Arista Records, LLC",
                    "performers": "Not Documented, Producer - Eric Idle, Composer, Lyricist - Terry Jones, Composer, Lyricist - John Cleese, Composer, Lyricist - Graham Chapman, Composer, Lyricist - Terry Gilliam, Composer, Lyricist - Monty Python, MainArtist, AssociatedPerformer - Michael Palin, Composer, Lyricist",
                    "audio_info": {
                        "replaygain_track_peak": 0.685974,
                        "replaygain_track_gain": -1.09,
                    },
                    "performer": {"name": "Monty Python", "id": 44279},
                    "work": None,
                    "composer": {"name": "Graham Chapman", "id": 675365},
                    "isrc": "USAR10700145",
                    "title": "Arthur And God",
                    "version": None,
                    "duration": 69,
                    "parental_warning": False,
                    "track_number": 9,
                    "maximum_channel_count": 2,
                    "id": 47062488,
                    "media_number": 1,
                    "maximum_sampling_rate": 44.1,
                    "release_date_original": None,
                    "release_date_download": None,
                    "release_date_stream": None,
                    "purchasable": True,
                    "streamable": True,
                    "previewable": True,
                    "sampleable": True,
                    "downloadable": True,
                    "displayable": True,
                    "purchasable_at": 1647932400,
                    "streamable_at": 1647932400,
                    "hires": False,
                    "hires_streamable": False,
                },
                {
                    "maximum_bit_depth": 16,
                    "copyright": "(P) 1975, 1997 Arista Records, LLC",
                    "performers": "Not Documented, Producer - Eric Idle, Composer, Lyricist - Terry Jones, Composer, Lyricist - John Cleese, Composer, Lyricist - Graham Chapman, Composer, Lyricist - Terry Gilliam, Composer, Lyricist - Monty Python, MainArtist, AssociatedPerformer - Michael Palin, Composer, Lyricist",
                    "audio_info": {
                        "replaygain_track_peak": 0.82547,
                        "replaygain_track_gain": -0.92,
                    },
                    "performer": {"name": "Monty Python", "id": 44279},
                    "work": None,
                    "composer": {"name": "Graham Chapman", "id": 675365},
                    "isrc": "USAR10700146",
                    "title": "Classic (Silbury Hill)",
                    "version": None,
                    "duration": 49,
                    "parental_warning": False,
                    "track_number": 10,
                    "maximum_channel_count": 2,
                    "id": 47062489,
                    "media_number": 1,
                    "maximum_sampling_rate": 44.1,
                    "release_date_original": None,
                    "release_date_download": None,
                    "release_date_stream": None,
                    "purchasable": True,
                    "streamable": True,
                    "previewable": True,
                    "sampleable": True,
                    "downloadable": True,
                    "displayable": True,
                    "purchasable_at": 1647932400,
                    "streamable_at": 1647932400,
                    "hires": False,
                    "hires_streamable": False,
                },
                {
                    "maximum_bit_depth": 16,
                    "copyright": "(P) 1975, 1997 Arista Records, LLC",
                    "performers": "Not Documented, Producer - Eric Idle, Composer, Lyricist - Terry Jones, Composer, Lyricist - John Cleese, Composer, Lyricist - Graham Chapman, Composer, Lyricist - Terry Gilliam, Composer, Lyricist - Monty Python, MainArtist, AssociatedPerformer - Michael Palin, Composer, Lyricist",
                    "audio_info": {
                        "replaygain_track_peak": 0.991455,
                        "replaygain_track_gain": -2.7,
                    },
                    "performer": {"name": "Monty Python", "id": 44279},
                    "work": None,
                    "composer": {"name": "Graham Chapman", "id": 675365},
                    "isrc": "USAR10700147",
                    "title": "French Castle",
                    "version": None,
                    "duration": 185,
                    "parental_warning": False,
                    "track_number": 11,
                    "maximum_channel_count": 2,
                    "id": 47062490,
                    "media_number": 1,
                    "maximum_sampling_rate": 44.1,
                    "release_date_original": None,
                    "release_date_download": None,
                    "release_date_stream": None,
                    "purchasable": True,
                    "streamable": True,
                    "previewable": True,
                    "sampleable": True,
                    "downloadable": True,
                    "displayable": True,
                    "purchasable_at": 1647932400,
                    "streamable_at": 1647932400,
                    "hires": False,
                    "hires_streamable": False,
                },
                {
                    "maximum_bit_depth": 16,
                    "copyright": "(P) 1975, 1997 Arista Records, LLC",
                    "performers": "Not Documented, Producer - Eric Idle, Composer, Lyricist - Terry Jones, Composer, Lyricist - John Cleese, Composer, Lyricist - Graham Chapman, Composer, Lyricist - Terry Gilliam, Composer, Lyricist - Monty Python, MainArtist, AssociatedPerformer - Michael Palin, Composer, Lyricist",
                    "audio_info": {
                        "replaygain_track_peak": 0.975281,
                        "replaygain_track_gain": -2.36,
                    },
                    "performer": {"name": "Monty Python", "id": 44279},
                    "work": None,
                    "composer": {"name": "Graham Chapman", "id": 675365},
                    "isrc": "USAR10700148",
                    "title": "Announcement",
                    "version": None,
                    "duration": 28,
                    "parental_warning": False,
                    "track_number": 12,
                    "maximum_channel_count": 2,
                    "id": 47062491,
                    "media_number": 1,
                    "maximum_sampling_rate": 44.1,
                    "release_date_original": None,
                    "release_date_download": None,
                    "release_date_stream": None,
                    "purchasable": True,
                    "streamable": True,
                    "previewable": True,
                    "sampleable": True,
                    "downloadable": True,
                    "displayable": True,
                    "purchasable_at": 1647932400,
                    "streamable_at": 1647932400,
                    "hires": False,
                    "hires_streamable": False,
                },
                {
                    "maximum_bit_depth": 16,
                    "copyright": "(P) 1975, 1997 Arista Records, LLC",
                    "performers": "Not Documented, Producer - Eric Idle, Composer, Lyricist - Terry Jones, Composer, Lyricist - John Cleese, Composer, Lyricist - Graham Chapman, Composer, Lyricist - Terry Gilliam, Composer, Lyricist - Monty Python, MainArtist, AssociatedPerformer - Michael Palin, Composer, Lyricist",
                    "audio_info": {
                        "replaygain_track_peak": 0.584625,
                        "replaygain_track_gain": 3.66,
                    },
                    "performer": {"name": "Monty Python", "id": 44279},
                    "work": None,
                    "composer": {"name": "Graham Chapman", "id": 675365},
                    "isrc": "USAR10700149",
                    "title": "Apology",
                    "version": None,
                    "duration": 18,
                    "parental_warning": False,
                    "track_number": 13,
                    "maximum_channel_count": 2,
                    "id": 47062492,
                    "media_number": 1,
                    "maximum_sampling_rate": 44.1,
                    "release_date_original": None,
                    "release_date_download": None,
                    "release_date_stream": None,
                    "purchasable": True,
                    "streamable": True,
                    "previewable": True,
                    "sampleable": True,
                    "downloadable": True,
                    "displayable": True,
                    "purchasable_at": 1647932400,
                    "streamable_at": 1647932400,
                    "hires": False,
                    "hires_streamable": False,
                },
                {
                    "maximum_bit_depth": 16,
                    "copyright": "(P) 1975, 1997 Arista Records, LLC",
                    "performers": "Not Documented, Producer - Eric Idle, Composer, Lyricist - Terry Jones, Composer, Lyricist - John Cleese, Composer, Lyricist - Graham Chapman, Composer, Lyricist - Terry Gilliam, Composer, Lyricist - Monty Python, MainArtist, AssociatedPerformer - Michael Palin, Composer, Lyricist",
                    "audio_info": {
                        "replaygain_track_peak": 0.990356,
                        "replaygain_track_gain": -0.92,
                    },
                    "performer": {"name": "Monty Python", "id": 44279},
                    "work": None,
                    "composer": {"name": "Graham Chapman", "id": 675365},
                    "isrc": "USAR10700150",
                    "title": "Story So Far",
                    "version": None,
                    "duration": 21,
                    "parental_warning": False,
                    "track_number": 14,
                    "maximum_channel_count": 2,
                    "id": 47062493,
                    "media_number": 1,
                    "maximum_sampling_rate": 44.1,
                    "release_date_original": None,
                    "release_date_download": None,
                    "release_date_stream": None,
                    "purchasable": True,
                    "streamable": True,
                    "previewable": True,
                    "sampleable": True,
                    "downloadable": True,
                    "displayable": True,
                    "purchasable_at": 1647932400,
                    "streamable_at": 1647932400,
                    "hires": False,
                    "hires_streamable": False,
                },
                {
                    "maximum_bit_depth": 16,
                    "copyright": "(P) 1975, 1997 Arista Records, LLC",
                    "performers": "Not Documented, Producer - Eric Idle, Composer, Lyricist - Neil Innes, Composer, Lyricist - Monty Python, MainArtist, AssociatedPerformer",
                    "audio_info": {
                        "replaygain_track_peak": 0.99057,
                        "replaygain_track_gain": -1.02,
                    },
                    "performer": {"name": "Monty Python", "id": 44279},
                    "work": None,
                    "composer": {"name": "Eric Idle", "id": 200057},
                    "isrc": "USAR10700151",
                    "title": "Brave Sir Robin",
                    "version": None,
                    "duration": 225,
                    "parental_warning": False,
                    "track_number": 15,
                    "maximum_channel_count": 2,
                    "id": 47062494,
                    "media_number": 1,
                    "maximum_sampling_rate": 44.1,
                    "release_date_original": None,
                    "release_date_download": None,
                    "release_date_stream": None,
                    "purchasable": True,
                    "streamable": True,
                    "previewable": True,
                    "sampleable": True,
                    "downloadable": True,
                    "displayable": True,
                    "purchasable_at": 1647932400,
                    "streamable_at": 1647932400,
                    "hires": False,
                    "hires_streamable": False,
                },
                {
                    "maximum_bit_depth": 16,
                    "copyright": "(P) 1975, 1997 Arista Records, LLC",
                    "performers": "Not Documented, Producer - Eric Idle, Composer, Lyricist - Terry Jones, Composer, Lyricist - John Cleese, Composer, Lyricist - Graham Chapman, Composer, Lyricist - Terry Gilliam, Composer, Lyricist - Monty Python, MainArtist, AssociatedPerformer - Michael Palin, Composer, Lyricist",
                    "audio_info": {
                        "replaygain_track_peak": 0.647827,
                        "replaygain_track_gain": 0.16,
                    },
                    "performer": {"name": "Monty Python", "id": 44279},
                    "work": None,
                    "composer": {"name": "Graham Chapman", "id": 675365},
                    "isrc": "USAR10700152",
                    "title": 'The Knights Who Say "Ni"',
                    "version": None,
                    "duration": 150,
                    "parental_warning": False,
                    "track_number": 16,
                    "maximum_channel_count": 2,
                    "id": 47062495,
                    "media_number": 1,
                    "maximum_sampling_rate": 44.1,
                    "release_date_original": None,
                    "release_date_download": None,
                    "release_date_stream": None,
                    "purchasable": True,
                    "streamable": True,
                    "previewable": True,
                    "sampleable": True,
                    "downloadable": True,
                    "displayable": True,
                    "purchasable_at": 1647932400,
                    "streamable_at": 1647932400,
                    "hires": False,
                    "hires_streamable": False,
                },
                {
                    "maximum_bit_depth": 16,
                    "copyright": "(P) 1975, 1997 Arista Records, LLC",
                    "performers": "Not Documented, Producer - Eric Idle, Composer, Lyricist - Terry Jones, Composer, Lyricist - John Cleese, Composer, Lyricist - Graham Chapman, Composer, Lyricist - Terry Gilliam, Composer, Lyricist - Monty Python, MainArtist, AssociatedPerformer - Michael Palin, Composer, Lyricist",
                    "audio_info": {
                        "replaygain_track_peak": 0.991058,
                        "replaygain_track_gain": -4.03,
                    },
                    "performer": {"name": "Monty Python", "id": 44279},
                    "work": None,
                    "composer": {"name": "Graham Chapman", "id": 675365},
                    "isrc": "USAR10700153",
                    "title": "Classic (Silbury Hill) (Part 2)",
                    "version": None,
                    "duration": 33,
                    "parental_warning": False,
                    "track_number": 17,
                    "maximum_channel_count": 2,
                    "id": 47062496,
                    "media_number": 1,
                    "maximum_sampling_rate": 44.1,
                    "release_date_original": None,
                    "release_date_download": None,
                    "release_date_stream": None,
                    "purchasable": True,
                    "streamable": True,
                    "previewable": True,
                    "sampleable": True,
                    "downloadable": True,
                    "displayable": True,
                    "purchasable_at": 1647932400,
                    "streamable_at": 1647932400,
                    "hires": False,
                    "hires_streamable": False,
                },
                {
                    "maximum_bit_depth": 16,
                    "copyright": "(P) 1975, 1997 Arista Records, LLC",
                    "performers": "Not Documented, Producer - Eric Idle, Composer, Lyricist - Terry Jones, Composer, Lyricist - John Cleese, Composer, Lyricist - Graham Chapman, Composer, Lyricist - Terry Gilliam, Composer, Lyricist - Monty Python, MainArtist, AssociatedPerformer - Michael Palin, Composer, Lyricist",
                    "audio_info": {
                        "replaygain_track_peak": 0.992035,
                        "replaygain_track_gain": -0.93,
                    },
                    "performer": {"name": "Monty Python", "id": 44279},
                    "work": None,
                    "composer": {"name": "Graham Chapman", "id": 675365},
                    "isrc": "USAR10700154",
                    "title": "Marilyn Monroe",
                    "version": None,
                    "duration": 130,
                    "parental_warning": False,
                    "track_number": 18,
                    "maximum_channel_count": 2,
                    "id": 47062497,
                    "media_number": 1,
                    "maximum_sampling_rate": 44.1,
                    "release_date_original": None,
                    "release_date_download": None,
                    "release_date_stream": None,
                    "purchasable": True,
                    "streamable": True,
                    "previewable": True,
                    "sampleable": True,
                    "downloadable": True,
                    "displayable": True,
                    "purchasable_at": 1647932400,
                    "streamable_at": 1647932400,
                    "hires": False,
                    "hires_streamable": False,
                },
                {
                    "maximum_bit_depth": 16,
                    "copyright": "(P) 1975, 1997 Arista Records, LLC",
                    "performers": "Not Documented, Producer - Eric Idle, Composer, Lyricist - Terry Jones, Composer, Lyricist - John Cleese, Composer, Lyricist - Graham Chapman, Composer, Lyricist - Terry Gilliam, Composer, Lyricist - Monty Python, MainArtist, AssociatedPerformer - Michael Palin, Composer, Lyricist",
                    "audio_info": {
                        "replaygain_track_peak": 0.990997,
                        "replaygain_track_gain": -0.92,
                    },
                    "performer": {"name": "Monty Python", "id": 44279},
                    "work": None,
                    "composer": {"name": "Graham Chapman", "id": 675365},
                    "isrc": "USAR10700155",
                    "title": "Sir Lancelot & Swamp",
                    "version": None,
                    "duration": 248,
                    "parental_warning": False,
                    "track_number": 19,
                    "maximum_channel_count": 2,
                    "id": 47062498,
                    "media_number": 1,
                    "maximum_sampling_rate": 44.1,
                    "release_date_original": None,
                    "release_date_download": None,
                    "release_date_stream": None,
                    "purchasable": True,
                    "streamable": True,
                    "previewable": True,
                    "sampleable": True,
                    "downloadable": True,
                    "displayable": True,
                    "purchasable_at": 1647932400,
                    "streamable_at": 1647932400,
                    "hires": False,
                    "hires_streamable": False,
                },
                {
                    "maximum_bit_depth": 16,
                    "copyright": "(P) 1975, 1997 Arista Records, LLC",
                    "performers": "Not Documented, Producer - Eric Idle, Composer, Lyricist - Terry Jones, Composer, Lyricist - John Cleese, Composer, Lyricist - Graham Chapman, Composer, Lyricist - Terry Gilliam, Composer, Lyricist - Monty Python, MainArtist, AssociatedPerformer - Michael Palin, Composer, Lyricist",
                    "audio_info": {
                        "replaygain_track_peak": 0.948059,
                        "replaygain_track_gain": -0.54,
                    },
                    "performer": {"name": "Monty Python", "id": 44279},
                    "work": None,
                    "composer": {"name": "Graham Chapman", "id": 675365},
                    "isrc": "USAR10700156",
                    "title": "Tim The Enchanter",
                    "version": None,
                    "duration": 38,
                    "parental_warning": False,
                    "track_number": 20,
                    "maximum_channel_count": 2,
                    "id": 47062499,
                    "media_number": 1,
                    "maximum_sampling_rate": 44.1,
                    "release_date_original": None,
                    "release_date_download": None,
                    "release_date_stream": None,
                    "purchasable": True,
                    "streamable": True,
                    "previewable": True,
                    "sampleable": True,
                    "downloadable": True,
                    "displayable": True,
                    "purchasable_at": 1647932400,
                    "streamable_at": 1647932400,
                    "hires": False,
                    "hires_streamable": False,
                },
                {
                    "maximum_bit_depth": 16,
                    "copyright": "(P) 1975, 1997 Arista Records, LLC",
                    "performers": "Not Documented, Producer - Eric Idle, Composer, Lyricist - Terry Jones, Composer, Lyricist - John Cleese, Composer, Lyricist - Graham Chapman, Composer, Lyricist - Terry Gilliam, Composer, Lyricist - Monty Python, MainArtist, AssociatedPerformer - Michael Palin, Composer, Lyricist",
                    "audio_info": {
                        "replaygain_track_peak": 0.989929,
                        "replaygain_track_gain": -2.16,
                    },
                    "performer": {"name": "Monty Python", "id": 44279},
                    "work": None,
                    "composer": {"name": "Graham Chapman", "id": 675365},
                    "isrc": "USAR10700157",
                    "title": "Drama Critic",
                    "version": None,
                    "duration": 163,
                    "parental_warning": False,
                    "track_number": 21,
                    "maximum_channel_count": 2,
                    "id": 47062500,
                    "media_number": 1,
                    "maximum_sampling_rate": 44.1,
                    "release_date_original": None,
                    "release_date_download": None,
                    "release_date_stream": None,
                    "purchasable": True,
                    "streamable": True,
                    "previewable": True,
                    "sampleable": True,
                    "downloadable": True,
                    "displayable": True,
                    "purchasable_at": 1647932400,
                    "streamable_at": 1647932400,
                    "hires": False,
                    "hires_streamable": False,
                },
                {
                    "maximum_bit_depth": 16,
                    "copyright": "(P) 1975, 1997 Arista Records, LLC",
                    "performers": "Not Documented, Producer - Eric Idle, Composer, Lyricist - Terry Jones, Composer, Lyricist - John Cleese, Composer, Lyricist - Graham Chapman, Composer, Lyricist - Terry Gilliam, Composer, Lyricist - Monty Python, MainArtist, AssociatedPerformer - Michael Palin, Composer, Lyricist",
                    "audio_info": {
                        "replaygain_track_peak": 0.653015,
                        "replaygain_track_gain": 2.7,
                    },
                    "performer": {"name": "Monty Python", "id": 44279},
                    "work": None,
                    "composer": {"name": "Graham Chapman", "id": 675365},
                    "isrc": "USAR10700158",
                    "title": "Hand Grenade Of Antioch",
                    "version": None,
                    "duration": 161,
                    "parental_warning": False,
                    "track_number": 22,
                    "maximum_channel_count": 2,
                    "id": 47062501,
                    "media_number": 1,
                    "maximum_sampling_rate": 44.1,
                    "release_date_original": None,
                    "release_date_download": None,
                    "release_date_stream": None,
                    "purchasable": True,
                    "streamable": True,
                    "previewable": True,
                    "sampleable": True,
                    "downloadable": True,
                    "displayable": True,
                    "purchasable_at": 1647932400,
                    "streamable_at": 1647932400,
                    "hires": False,
                    "hires_streamable": False,
                },
                {
                    "maximum_bit_depth": 16,
                    "copyright": "(P) 1975, 1997 Arista Records, LLC",
                    "performers": "Not Documented, Producer - Eric Idle, Composer, Lyricist - Terry Jones, Composer, Lyricist - John Cleese, Composer, Lyricist - Graham Chapman, Composer, Lyricist - Terry Gilliam, Composer, Lyricist - Monty Python, MainArtist, AssociatedPerformer - Michael Palin, Composer, Lyricist",
                    "audio_info": {
                        "replaygain_track_peak": 0.930084,
                        "replaygain_track_gain": -0.37,
                    },
                    "performer": {"name": "Monty Python", "id": 44279},
                    "work": None,
                    "composer": {"name": "Graham Chapman", "id": 675365},
                    "isrc": "USAR10700159",
                    "title": "Announcement (Part 2)",
                    "version": None,
                    "duration": 54,
                    "parental_warning": False,
                    "track_number": 23,
                    "maximum_channel_count": 2,
                    "id": 47062502,
                    "media_number": 1,
                    "maximum_sampling_rate": 44.1,
                    "release_date_original": None,
                    "release_date_download": None,
                    "release_date_stream": None,
                    "purchasable": True,
                    "streamable": True,
                    "previewable": True,
                    "sampleable": True,
                    "downloadable": True,
                    "displayable": True,
                    "purchasable_at": 1647932400,
                    "streamable_at": 1647932400,
                    "hires": False,
                    "hires_streamable": False,
                },
                {
                    "maximum_bit_depth": 16,
                    "copyright": "(P) 1975, 1997 Arista Records, LLC",
                    "performers": "Not Documented, Producer - Eric Idle, Composer, Lyricist - Terry Jones, Composer, Lyricist - John Cleese, Composer, Lyricist - Graham Chapman, Composer, Lyricist - Terry Gilliam, Composer, Lyricist - Monty Python, MainArtist, AssociatedPerformer - Michael Palin, Composer, Lyricist",
                    "audio_info": {
                        "replaygain_track_peak": 0.800964,
                        "replaygain_track_gain": -0.21,
                    },
                    "performer": {"name": "Monty Python", "id": 44279},
                    "work": None,
                    "composer": {"name": "Graham Chapman", "id": 675365},
                    "isrc": "USAR10700160",
                    "title": "End Of Quest",
                    "version": None,
                    "duration": 166,
                    "parental_warning": False,
                    "track_number": 24,
                    "maximum_channel_count": 2,
                    "id": 47062503,
                    "media_number": 1,
                    "maximum_sampling_rate": 44.1,
                    "release_date_original": None,
                    "release_date_download": None,
                    "release_date_stream": None,
                    "purchasable": True,
                    "streamable": True,
                    "previewable": True,
                    "sampleable": True,
                    "downloadable": True,
                    "displayable": True,
                    "purchasable_at": 1647932400,
                    "streamable_at": 1647932400,
                    "hires": False,
                    "hires_streamable": False,
                },
                {
                    "maximum_bit_depth": 16,
                    "copyright": "(P) 2006 Arista Records, LLC",
                    "performers": "Not Documented, Producer - Neil Innes, Composer, Lyricist - Monty Python, MainArtist, AssociatedPerformer",
                    "audio_info": {
                        "replaygain_track_peak": 0.708252,
                        "replaygain_track_gain": -0.45,
                    },
                    "performer": {"name": "Monty Python", "id": 44279},
                    "work": None,
                    "composer": {"name": "Neil Innes", "id": 388624},
                    "isrc": "USAR10700161",
                    "title": "Arthur\\s Song",
                    "version": None,
                    "duration": 150,
                    "parental_warning": False,
                    "track_number": 25,
                    "maximum_channel_count": 2,
                    "id": 47062504,
                    "media_number": 1,
                    "maximum_sampling_rate": 44.1,
                    "release_date_original": None,
                    "release_date_download": None,
                    "release_date_stream": None,
                    "purchasable": True,
                    "streamable": True,
                    "previewable": True,
                    "sampleable": True,
                    "downloadable": True,
                    "displayable": True,
                    "purchasable_at": 1647932400,
                    "streamable_at": 1647932400,
                    "hires": False,
                    "hires_streamable": False,
                },
                {
                    "maximum_bit_depth": 16,
                    "copyright": "(P) 2006 Arista Records, LLC",
                    "performers": "Not Documented, Producer - Spoken Word, Lyricist - Monty Python, MainArtist, AssociatedPerformer",
                    "audio_info": {
                        "replaygain_track_peak": 0.644958,
                        "replaygain_track_gain": 2.07,
                    },
                    "performer": {"name": "Monty Python", "id": 44279},
                    "work": None,
                    "isrc": "USAR10700162",
                    "title": "Documentary - Terry Jones And Michael Palin",
                    "version": None,
                    "duration": 347,
                    "parental_warning": False,
                    "track_number": 26,
                    "maximum_channel_count": 2,
                    "id": 47062505,
                    "media_number": 1,
                    "maximum_sampling_rate": 44.1,
                    "release_date_original": None,
                    "release_date_download": None,
                    "release_date_stream": None,
                    "purchasable": True,
                    "streamable": True,
                    "previewable": True,
                    "sampleable": True,
                    "downloadable": True,
                    "displayable": True,
                    "purchasable_at": 1647932400,
                    "streamable_at": 1647932400,
                    "hires": False,
                    "hires_streamable": False,
                },
                {
                    "maximum_bit_depth": 16,
                    "copyright": "(P) 2006 Arista Records, LLC",
                    "performers": "Not Documented, Producer - Neil Innes, Composer, Lyricist - Monty Python, MainArtist, AssociatedPerformer",
                    "audio_info": {
                        "replaygain_track_peak": 0.66861,
                        "replaygain_track_gain": 0.06,
                    },
                    "performer": {"name": "Monty Python", "id": 44279},
                    "work": None,
                    "composer": {"name": "Neil Innes", "id": 388624},
                    "isrc": "USAR10700163",
                    "title": "Run Away Song",
                    "version": None,
                    "duration": 147,
                    "parental_warning": False,
                    "track_number": 27,
                    "maximum_channel_count": 2,
                    "id": 47062506,
                    "media_number": 1,
                    "maximum_sampling_rate": 44.1,
                    "release_date_original": None,
                    "release_date_download": None,
                    "release_date_stream": None,
                    "purchasable": True,
                    "streamable": True,
                    "previewable": True,
                    "sampleable": True,
                    "downloadable": True,
                    "displayable": True,
                    "purchasable_at": 1647932400,
                    "streamable_at": 1647932400,
                    "hires": False,
                    "hires_streamable": False,
                },
            ],
        ),
        parental_warning=False,
        image=dict(
            small="https://static.qobuz.com/images/covers/qb/ws/lj1s9oz62wsqb_230.jpg",
            thumbnail="https://static.qobuz.com/images/covers/qb/ws/lj1s9oz62wsqb_50.jpg",
            large="https://static.qobuz.com/images/covers/qb/ws/lj1s9oz62wsqb_600.jpg",
            back=None,
        ),
        streamable=True,
        maximum_bit_depth=16,
        maximum_sampling_rate=44.1,
        goodies=[],
    )
