name: 🐛 Bug Report
description: Create a report to help us improve streamrip
labels: bug
title: "[BUG] <title>"
body:
  # types: dropdown, textarea, input
  # - type: dropdown
  #   validations:
  #     required: true
  #   attributes:
  #     label: Are you using "tree-sitter" branch?
  #     options:
  #       - 'Yes'
  #       - 'No'

  - type: textarea
    validations:
      required: true
    attributes:
      label: Describe the bug
      description: A clear and concise description of the bug.

  - type: textarea
    validations:
      required: true
    attributes:
      label: Command Used
      description: |
        The command that you typed that caused the error
      placeholder: e.g. rip url https://example.com
      render: "bash"

  - type: textarea
    validations:
      required: true
    attributes:
      label: Debug Traceback
      description: |
        Run your command, with `-vvv` appended to it, and paste the output here.
        For example, if the problematic command was `rip url https://example.com`, then
        you would run `rip url https://example.com -vvv` to get the debug logs.
        Make sure to check the logs for any personal information such as emails and remove them.
      render: "text"
      placeholder: Logs printed to terminal screen

  - type: textarea
    validations:
      required: true
    attributes:
      label: Config File
      description: |
        Find the config file using `rip config --open` and paste the contents here. 
        Make sure you REMOVE YOUR CREDENTIALS!
      render: toml
      placeholder: Contents of config.toml

  - type: input
    validations:
      required: true
    attributes:
      label: Operating System
      placeholder: e.g. Windows, Linux, macOS...

  - type: input
    validations:
      required: true
    attributes:
      label: streamrip version
      description: Run `rip --version` to check.
      placeholder: e.g. 1.5

  - type: textarea
    attributes:
      label: Screenshots and recordings
      description: |
        If applicable, add screenshots to help explain your problem.
        You can also record an asciinema session: https://asciinema.org/

  - type: textarea
    attributes:
      label: Additional context
      description: Add any other context about the problem here.

  - type: markdown
    attributes:
      value: "Thanks for completing our form!"
