name: Ruff

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

jobs:
  ruff:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - name: Run ruff check
        uses: astral-sh/ruff-action@v3
